on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    name: release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y musl-tools gcc-mingw-w64-x86-64

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy
          override: true
          target: x86_64-unknown-linux-musl

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.7.7

      - name: clippy check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: install cargo-license
        uses: actions-rs/cargo@v1.0.3
        with:
          command: install
          args: cargo-license

      - name: compile for unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --no-run --locked

      - name: unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu

      - run: |
          mkdir png2mozjpegd
          cargo license \
            --authors \
            --do-not-bundle \
            --avoid-dev-deps \
            --avoid-build-deps \
            --filter-platform x86_64-pc-windows-gnu \
              > png2mozjpegd/CREDITS
          VERSION_NAME=${GITHUB_REF##*/}
          if [[ $VERSION_NAME == "master" ]]; then
              VERSION_NAME=$(git rev-parse --short HEAD)
          elif [[ ${VERSION_NAME:0:1} == "v" ]]; then
              VERSION_NAME=${VERSION_NAME:1}
          fi
          echo "$VERSION_NAME" > png2mozjpegd/VERSION.txt
          printf "png2mozjpegd\r\npause\r\n" > png2mozjpegd/png2mozjpegd-debug.bat
          cp config.yml LICENSE README.md png2mozjpegd/
          cp target/x86_64-pc-windows-gnu/release/png2mozjpegd.exe png2mozjpegd/
          zip -r png2mozjpegd-windows.zip png2mozjpegd
          rm png2mozjpegd/*.{exe,bat}
          cargo license \
            --authors \
            --do-not-bundle \
            --avoid-dev-deps \
            --avoid-build-deps \
            --filter-platform x86_64-unknown-linux-gnu \
              > png2mozjpegd/CREDITS
          cp target/x86_64-unknown-linux-musl/release/png2mozjpegd png2mozjpegd/
          zip -r png2mozjpegd-linux.zip png2mozjpegd

      - name: pre-release
        uses: softprops/action-gh-release@v2.0.5
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          tag_name: "latest"
          prerelease: true
          name: "Development Build"
          files: |
            png2mozjpegd-windows.zip
            png2mozjpegd-linux.zip

      - name: tagged-release
        uses: softprops/action-gh-release@v2.0.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            png2mozjpegd-windows.zip
            png2mozjpegd-linux.zip
